server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fraud_db
    redis:
      host: localhost
      port: 6379

ml:
  service:
    base-url: http://localhost:8000
    predict-path: /ml/predict-risk

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  redis:
    enabled: false